"""Property-based tests for the Metrics_Engine (tasks 13.2 and 13.3).

These tests drive the real :class:`~analyzer.metrics.MetricsEngine` over
datasets generated by the shared :func:`~tests.strategies.record_lists`
strategy, together with a subset of :class:`~analyzer.models.QualityIssue`
objects that reference some of the records' locations. They assert the
universal metric invariants (Property 8) and the documented empty-dataset
zero values (Property 9).

Issues are mapped to records by :class:`~analyzer.models.RecordLocation`, so the
expected ``issue_record_proportion`` is the number of records whose location is
referenced by at least one issue divided by the record count, mirroring the
engine's own definition. Dataset-level issues (``location is None``) reference
no record and are excluded.
"""

from __future__ import annotations

from hypothesis import given, settings
from hypothesis import strategies as st

from analyzer.metrics import MetricsEngine, token_count
from analyzer.models import (
    Dataset,
    IssueCategory,
    QualityIssue,
    RecordLocation,
)
from tests.strategies import record_lists

_ALL_CATEGORIES = list(IssueCategory)


@st.composite
def _datasets_with_issues(draw):
    """A (Dataset, issues) pair where issues reference a subset of records.

    The records come from the shared ``record_lists`` strategy (which may yield
    an empty list). Issues are built by sampling a subset of the generated
    records and attaching an issue at each sampled record's location, plus an
    arbitrary number of dataset-level issues (``location is None``).
    """
    records = draw(record_lists(min_size=0, max_size=6))

    issues: list[QualityIssue] = []
    if records:
        flagged_indices = draw(
            st.lists(
                st.integers(min_value=0, max_value=len(records) - 1),
                max_size=len(records) * 2,
            )
        )
        for index in flagged_indices:
            issues.append(
                QualityIssue(
                    category=draw(st.sampled_from(_ALL_CATEGORIES)),
                    location=records[index].location,
                )
            )

    # A handful of dataset-level issues that must not affect the proportion.
    for _ in range(draw(st.integers(min_value=0, max_value=3))):
        issues.append(
            QualityIssue(
                category=IssueCategory.SCHEMA_INFERENCE_FAILED, location=None
            )
        )

    dataset = Dataset(records=records, source_files=["data"])
    return dataset, issues


# Feature: llm-training-data-quality-analyzer, Property 8: Metric invariants over any dataset
@settings(max_examples=100, deadline=None)
@given(data=_datasets_with_issues())
def test_metric_invariants_over_any_dataset(data):
    """Metric bounds and definitions hold for any dataset and its issues.

    Validates Requirements 4.1, 4.2, 4.3, 4.4.
    """
    dataset, issues = data
    metrics = MetricsEngine().compute(dataset, issues)

    records = dataset.records

    # 4.1: record_count is the non-negative number of records.
    assert metrics.record_count == len(records)
    assert metrics.record_count >= 0

    if records:
        # 4.2: token-count statistics are ordered, non-negative integers, and
        # min/max equal the actual per-record token-count extremes.
        token_counts = [token_count(record) for record in records]
        assert isinstance(metrics.min_tokens, int)
        assert isinstance(metrics.mean_tokens, int)
        assert isinstance(metrics.max_tokens, int)
        assert 0 <= metrics.min_tokens <= metrics.mean_tokens <= metrics.max_tokens
        assert metrics.min_tokens == min(token_counts)
        assert metrics.max_tokens == max(token_counts)

        # 4.3: issue_record_proportion is the share of records carrying at least
        # one issue (mapped by location), bounded in [0.0, 1.0].
        issue_locations: set[RecordLocation] = {
            issue.location for issue in issues if issue.location is not None
        }
        records_with_issues = sum(
            1 for record in records if record.location in issue_locations
        )
        expected_proportion = records_with_issues / len(records)
        assert metrics.issue_record_proportion == expected_proportion
        assert 0.0 <= metrics.issue_record_proportion <= 1.0

        # 4.4: quality_score = 1.0 - proportion, bounded in [0.0, 1.0].
        assert metrics.quality_score == 1.0 - metrics.issue_record_proportion
        assert 0.0 <= metrics.quality_score <= 1.0


@st.composite
def _arbitrary_issues(draw):
    """An arbitrary list of issues, some referencing arbitrary record locations."""
    issues: list[QualityIssue] = []
    for _ in range(draw(st.integers(min_value=0, max_value=5))):
        has_location = draw(st.booleans())
        location = (
            RecordLocation(
                source_file="data",
                array_index=draw(st.integers(min_value=0, max_value=100)),
            )
            if has_location
            else None
        )
        issues.append(
            QualityIssue(
                category=draw(st.sampled_from(_ALL_CATEGORIES)), location=location
            )
        )
    return issues


# Feature: llm-training-data-quality-analyzer, Property 9: Empty dataset metrics
@settings(max_examples=100, deadline=None)
@given(issues=_arbitrary_issues())
def test_empty_dataset_metrics(issues):
    """An empty dataset yields zeroed metrics regardless of accumulated issues.

    Validates Requirements 4.5, 4.6, 4.7.
    """
    metrics = MetricsEngine().compute(Dataset(records=[], source_files=["data"]), issues)

    assert metrics.record_count == 0
    # 4.6: mean/min/max token counts are 0 for an empty dataset.
    assert metrics.mean_tokens == 0
    assert metrics.min_tokens == 0
    assert metrics.max_tokens == 0
    # 4.7: issue-record proportion is 0.0 for an empty dataset.
    assert metrics.issue_record_proportion == 0.0
    # 4.5: quality score is 0.0 for an empty dataset.
    assert metrics.quality_score == 0.0
